---
title: "Supplement"
execute: 
  echo: false
format:
  docx: 
    reference-doc: word-style-reference-manuscript.docx
  html: default
bibliography: biball.bib
csl: american-medical-association-brackets.csl
#csl: apa.csl # Change the citation format to APA if preferred
editor: visual
crossref: 
  thm-title: "Table"
  thm-prefix: "Table"
  cor-title: "Table S"
  cor-prefix: "Table S"
  lem-title: "Figure S"
  lem-prefix: "Figure S"
  fig-title: "**Figure**"
---

```{r setup, include=FALSE}
library(ggplot2)            # plots
library(RefManageR)         # read/merge/write .bib file with R
library(data.table)         # for using datatables instead of frames
library(scales)             # formatting plot legends and text
library(readxl)             # read.excel
library(flextable)          # generating tables
```

Here we describe additional details about the methodology used.

## Dataset

The Canadian Longitudinal Study on Aging (CLSA) is a comprehensive national long-term study designed to track approximately 50,000 individuals aged 45 to 85 years at recruitment for a minimum of 20 years [@Raina2019]. During the COVID-19 pandemic, several studies were conducted to collect and analyze blood samples from CLSA participants, aimed at comprehending and evaluating the pandemic's population-level health impact.\
The dataset utilized in this study was sourced from the CLSA COVID-19 Antibody Study, with over 19,000 CLSA participants across ten provinces included \[Insert citation here\]. The dataset comprises demographic information, self-reported health status, vaccination and hospitalization history, and the results of SARS-CoV-2 immunoassay tests.

The CLSA COVID-19 Antibody Study has two complementary cohorts. The first one is called "comprehensive cohort", in which 17,399 participants were invited and 9,753 of them agreed to participant and provided testable samples with complete results. Within this group, N=4,258 contributed venous blood samples, and N=5,495 provided dried blood samples. Participants in the comprehensive cohort were randomly selected from locations within 25-50 km of the data collection sites (DCS) and underwent in-person interviews, providing detailed information on demographics, physical and mental health status, as well as vaccination and hospitalization history. The second cohort, known as the "tracking cohort," was interviewed by telephone. For our analysis, we will exclusively utilize data from the comprehensive cohort (N\>9,753), as it provides more comprehensive demographic and health condition data.

\[Can we cite the CLSA flow chart here? or is it OK to make our own version of it and put it here?\]

## Bivariate Analysis and Multivariate Regression Modeling

Before conducting propensity score weighting to calculate weights for each observations and analyze the weighted data, we performed an initial unadjusted bivariate analysis to compare the DBS and VBS groups. Additionally, we developed multivariate logistic regression models, regressing VBS/DBS against demographic factors, physical and mental health conditions, travel distance, vaccination status, and time since the last COVID outbreak. The comprehensive results generated by those simple logistic regression models and the full model are displayed in **Table X** and the odds ratio plot (**Fig. X**).

Upon completion of the full model, we constructed a best-fit model utilizing a backward stepwise model selection strategy. The model with lowest Akaike Information Criterion (AIC) value was selected as the best-fit model. Subsequently, we applied this best-fit model to calculate propensity scores for the selection of VBS over DBS. Participants from both groups will then be weighteded based on their propensity scores using Inverse probability of treatment weighting (IPTW).

By-province analysis results

## Analysis with Weighted Data

To analyze the variation in quantitative Anti-S immunoassay results, we employed the weighted empirical cumulative distribution function (eCDF) to visualize the distribution in the matched DBS and VBS cohorts (**Fig. Y**). We used Kolmogorov-Smirnov (KS) Test to assess whether the distributions are statistically-significantly different. Additionally, we utilized odds ratios to present differences in Anti-N and Anti-S assay positivity (**Table Y**).

<br>

# References

::: {#refs}
:::
